config/routes.rb
Flipstream::Application.routes.draw do
  resources :keywords

  resources :genres

  resources :subcategories

  resources :countries

  resources :categories

  resources :feeds

  root :to => 'home#index'

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_one   :country
  has_one   :category
  has_many  :keywords
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feed = Feed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(params[:feed])

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, :notice => 'Feed was successfully created.' }
        format.json { render :json => @feed, :status => :created, :location => @feed }
      else
        format.html { render :action => "new" }
        format.json { render :json => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to @feed, :notice => 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description_short %><br />
    <%= f.text_area :description_short %>
  </div>
  <div class="field">
    <%= f.label :description_long %><br />
    <%= f.text_area :description_long %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_area :keywords %>
  </div>
  <div class="field">
    <%= f.label :itunes_id %><br />
    <%= f.number_field :itunes_id %>
  </div>
  <div class="field">
    <%= f.label :artist_id %><br />
    <%= f.number_field :artist_id %>
  </div>
  <div class="field">
    <%= f.label :genre_id %><br />
    <%= f.number_field :genre_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :subcategory %><br />
    <%= f.number_field :subcategory %>
  </div>
  <div class="field">
    <%= f.label :release_date %><br />
    <%= f.datetime_select :release_date %>
  </div>
  <div class="field">
    <%= f.label :crawl_date %><br />
    <%= f.datetime_select :crawl_date %>
  </div>
  <div class="field">
    <%= f.label :is_video %><br />
    <%= f.check_box :is_video %>
  </div>
  <div class="field">
    <%= f.label :explicit %><br />
    <%= f.check_box :explicit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Listing feeds</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Name</th>
    <th>Description short</th>
    <th>Description long</th>
    <th>Keywords</th>
    <th>Itunes</th>
    <th>Artist</th>
    <th>Genre</th>
    <th>Category</th>
    <th>Subcategory</th>
    <th>Release date</th>
    <th>Crawl date</th>
    <th>Is video</th>
    <th>Explicit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feeds.each do |feed| %>
  <tr>
    <td><%= feed.url %></td>
    <td><%= feed.name %></td>
    <td><%= feed.description_short %></td>
    <td><%= feed.description_long %></td>
    <td><%= feed.keywords %></td>
    <td><%= feed.itunes_id %></td>
    <td><%= feed.artist_id %></td>
    <td><%= feed.genre_id %></td>
    <td><%= feed.category_id %></td>
    <td><%= feed.subcategory %></td>
    <td><%= feed.release_date %></td>
    <td><%= feed.crawl_date %></td>
    <td><%= feed.is_video %></td>
    <td><%= feed.explicit %></td>
    <td><%= link_to 'Show', feed %></td>
    <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
    <td><%= link_to 'Destroy', feed, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @feed.url %>
</p>

<p>
  <b>Name:</b>
  <%= @feed.name %>
</p>

<p>
  <b>Description short:</b>
  <%= @feed.description_short %>
</p>

<p>
  <b>Description long:</b>
  <%= @feed.description_long %>
</p>

<p>
  <b>Keywords:</b>
  <%= @feed.keywords %>
</p>

<p>
  <b>Itunes:</b>
  <%= @feed.itunes_id %>
</p>

<p>
  <b>Artist:</b>
  <%= @feed.artist_id %>
</p>

<p>
  <b>Genre:</b>
  <%= @feed.genre_id %>
</p>

<p>
  <b>Category:</b>
  <%= @feed.category_id %>
</p>

<p>
  <b>Subcategory:</b>
  <%= @feed.subcategory %>
</p>

<p>
  <b>Release date:</b>
  <%= @feed.release_date %>
</p>

<p>
  <b>Crawl date:</b>
  <%= @feed.crawl_date %>
</p>

<p>
  <b>Is video:</b>
  <%= @feed.is_video %>
</p>

<p>
  <b>Explicit:</b>
  <%= @feed.explicit %>
</p>


<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>