config/routes.rb
Flipstream::Application.routes.draw do
  resources :keywords

  resources :genres

  resources :subcategories

  resources :countries

  resources :categories

  resources :feeds

  root :to => 'home#index'

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  # GET /subcategories
  # GET /subcategories.json
  def index
    @subcategories = Subcategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @subcategories }
    end
  end

  # GET /subcategories/1
  # GET /subcategories/1.json
  def show
    @subcategory = Subcategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @subcategory }
    end
  end

  # GET /subcategories/new
  # GET /subcategories/new.json
  def new
    @subcategory = Subcategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @subcategory }
    end
  end

  # GET /subcategories/1/edit
  def edit
    @subcategory = Subcategory.find(params[:id])
  end

  # POST /subcategories
  # POST /subcategories.json
  def create
    @subcategory = Subcategory.new(params[:subcategory])

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to @subcategory, :notice => 'Subcategory was successfully created.' }
        format.json { render :json => @subcategory, :status => :created, :location => @subcategory }
      else
        format.html { render :action => "new" }
        format.json { render :json => @subcategory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /subcategories/1
  # PUT /subcategories/1.json
  def update
    @subcategory = Subcategory.find(params[:id])

    respond_to do |format|
      if @subcategory.update_attributes(params[:subcategory])
        format.html { redirect_to @subcategory, :notice => 'Subcategory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @subcategory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1
  # DELETE /subcategories/1.json
  def destroy
    @subcategory = Subcategory.find(params[:id])
    @subcategory.destroy

    respond_to do |format|
      format.html { redirect_to subcategories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<%= form_for(@subcategory) do |f| %>
  <% if @subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
      <% @subcategory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :itunes_id %><br />
    <%= f.number_field :itunes_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcategories/edit.html.erb
<h1>Editing subcategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcategory %> |
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/index.html.erb
<h1>Listing subcategories</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Itunes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subcategories.each do |subcategory| %>
  <tr>
    <td><%= subcategory.title %></td>
    <td><%= subcategory.itunes_id %></td>
    <td><%= link_to 'Show', subcategory %></td>
    <td><%= link_to 'Edit', edit_subcategory_path(subcategory) %></td>
    <td><%= link_to 'Destroy', subcategory, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subcategory', new_subcategory_path %>

app/views/subcategories/new.html.erb
<h1>New subcategory</h1>

<%= render 'form' %>

<%= link_to 'Back', subcategories_path %>

app/views/subcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @subcategory.title %>
</p>

<p>
  <b>Itunes:</b>
  <%= @subcategory.itunes_id %>
</p>


<%= link_to 'Edit', edit_subcategory_path(@subcategory) %> |
<%= link_to 'Back', subcategories_path %>